### ISSUE TITLE
Sphere Distillation empties the stack

### ISSUE THREAD

**Issue by sedyh** [Sonunte/HexKinetics#17]
Hello, it looks like drawing "Sphere Distillation" creates garbage, which then (after reopening the hexcasting ui) empties the stack.

Before:
![2023-09-04_21 00 55](https://github.com/Sonunte/HexKinetics/assets/19890545/f5fcaa93-4a75-4d1f-aa41-ca03ac6ccfea)

After:
![2023-09-04_21 01 05](https://github.com/Sonunte/HexKinetics/assets/19890545/44dcb6fb-1f2b-485a-ad65-b44a030a2a37)

Reopen:
![2023-09-04_21 01 12](https://github.com/Sonunte/HexKinetics/assets/19890545/d57ffda1-c439-4db7-85a9-e5895f1d7ba6)

**Comment by sedyh** [comment]
Also, erasing and redrawing the pattern causes the garbage to reappear, but that's not the list.
![image](https://github.com/Sonunte/HexKinetics/assets/19890545/627224c7-0eb7-4ddd-ae13-7c513163132f)

**Comment by Castone22** [comment]
Hexcasting has a limit on how large of an iota it can serialize, A radius of 10 will generate a list of ~240 points, and the max size hex can handle is like 200, otherwise it throws an error which gets handled as a generic mishap that clears your stack.

**Comment by sedyh** [comment]
Can I increase the limit?
Cause radius 10 isn't that big (quite small in fact).
